server:
  host: localhost
  port: 8080
  auto_relation: true
  session_max_age: 604800
database:
  username: root
  password: root
  host: 127.0.0.1
  port: 13306
  name: gcmdb
cors:
  allowed_origins: []
token_cache_ttl: 5
